{% set version = "2.68.0.51" %}

package:
  name: newrelic
  version: {{ version }}

source:
  fn: newrelic-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/newrelic/newrelic-{{ version }}.tar.gz
  sha256: 54e1da319d4670b4887b463309907cbefeff847a26e378609d04126a14d01b13

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - libtool  # [unix]
    - python
    - setuptools
    - toolchain
  run:
    - python
    - setuptools

test:
  requires:
    - python
  imports:
    - newrelic
  commands:
    - newrelic-admin help  # [unix]

about:
  home: http://newrelic.com/docs/python/new-relic-for-python
  license: New Relic License
  license_file: newrelic/LICENSE  # [unix]
  license_file: newrelic\LICENSE  # [win]
  summary: New Relic Python Agent

extra:
  recipe-maintainers:
    - bollwyvl
