{% set name = "newrelic" %}
{% set version = "2.106.1.88" %}
{% set sha256 = "0594dd63d7883d30c560e292d063a8dbc7b2ae11b889bec1e8eb9d0f11ab73a6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - newrelic-admin = newrelic.admin:main

requirements:
  build:
    - libtool  # [unix]
    - python
    - setuptools
    - pip
    - toolchain
  run:
    - python
    - setuptools

test:
  requires:
    - python
  imports:
    - newrelic
  commands:
    - newrelic-admin help  # [unix]

about:
  home: http://newrelic.com/docs/python/new-relic-for-python
  license: New Relic
  license_file: newrelic/LICENSE
  summary: New Relic Python Agent
  description: |
    The newrelic package instruments your application for performance
    monitoring and advanced performance analytics with New Relic.

    Pinpoint and solve Python application performance issues down to the line
    of code. New Relic APM is the only tool you’ll need to see everything in
    your Python application, from the end user experience to server monitoring.
    Trace problems down to slow database queries, slow 3rd party APIs and web
    services, caching layers, and more. Monitor your app in a production
    environment and make sure your app can stand a big spike in traffic by
    running scalability reports.

extra:
  recipe-maintainers:
    - bollwyvl
