appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eluMaWIK3FL2cyNAQDAVypcNUxd9GkFmxsW33InHHOlGmGECGM81eXNYrB2QPjKqYq5M11NEoR+FSDP5my5t+8PC6Q0owQ7F+gRBM3rUP1kbOnhSesmP9VJYcEI0cP9IhDvArf8S49XaKo639LnzPDkw1Ct5qa8ZGFsY9egeGdI357uOp67Ow7gg7OvW0uemvx3+Q82Lknn0Bc2z+WBXyBBaKeFpxzUMx/b4s6kyJxrLzgb06iTcRFuse8vLKmJWsYq5JpS639jBLAVg2vTJnxWJk2CP+rt3Y0wsiiss6OEVqAZlP+jZGxqUHJEtkxIrIzm+Gd/UMW6/ytA1mTs8uJFUrbzGHhfKtwqu+3WYVXs3pwS2ijbnmf85mkjogF9nt4C/BKHViHfDS4wP6AigNGvPHOQIyibUWyJC/K/tBuEJcjZZIYMx/0pjr+COuawQvdBjA9oEM+T9cbhZxhPipAdNMdWTiVaZBd4U0tVLR8PWIxXiUC6GRG7HPOMsicgheqwCSL0eyM5ToBdVh3P+VurvMzTcxu5FUgYQUpkvpsPcbtUcykFraUY9MvlTi8HXLZxCHYV0aAgKdfF9K+ekAyJEVr/Z8SiejPqpahOcOGELTfV3QUOv3fDmvR0kqpxcJ9L1bEMANWvFEc2cQ/QCpOOn1mFAv88Ophd1QioStSs=}
